version: '2.0'
services:
  config-server:
    image: coreal/jenkins
    user: root
    container_name: jenkins_blueocean
    ports:
     - "9080:8080"
     - "50000:50000"
    volumes:
     - "/applis/ms-sample/logs/config-server:/applis/ms-sample/logs/config-server"
     - "/var/run/docker.sock:/var/run/docker.sock" 
     - "/opt/apache-maven-3.3.9:/opt/apache-maven-3.3.9"
     - "/home/thales/dev-tools/sonar-scanner-3.0.3.778-linux:/opt/sonar-scanner"
     - "/home/thales/jenkins2:/var/jenkins_home"
    environment:
     - M2_HOME='/opt/apache-maven-3.3.9'
